version: "3.7"
services:
  user_service:
    build:
      context: ./
      dockerfile: ./user_service/Dockerfile
    image: user_service_image:latest
    ports:
      - "8000:5000"
    networks:
      - todo_network

#  task_service:
#    build:
#      context: ./task_service/task_app
#      dockerfile: ./Dockerfile
#    image: task_service_image:latest
#    ports:
#      - "8000:8000"
#    networks:
#      - todo_network
#
#  redis:
#    image: 'bitnami/redis:latest'
#    environment:
#      - ALLOW_EMPTY_PASSWORD=yes
#    networks:
#      - todo_network

  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DATABASE: users_db
    ports:
      - 5433:5432
#    environment:
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: example
#      POSTGRES_DATABASE: users_db
    networks:
      - todo_network


  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

networks:
  todo_network:
    driver: bridge
    name: todo_network