version: "3.7"
services:
  user_service:
    restart: on-failure
    build:
      context: ./
      dockerfile: ./user_service/Dockerfile
    image: user_service_image:latest
    depends_on:
      - postgres
    ports:
      - 5000:5000
    networks:
      - todo_network

  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: users_db
#      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5432:5432
    networks:
      - todo_network


  adminer:
    image: adminer
    restart: always
    depends_on:

      - postgres
    ports:
      - 8080:8080
    networks:
      - todo_network

networks:
  todo_network:
    driver: bridge
    name: todo_network